# -*- coding: utf-8 -*-
"""FindAddress.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16s_MkCmb6ZEXHyygSd3yJSlkyBHXHuef
"""

!pip install arcgis

from arcgis.gis import GIS
from arcgis.geocoding import geocode, reverse_geocode
from arcgis.geometry import Point

gis = GIS()

for x in geocode_result.features:
    gdpoint = x.as_dict["geometry"]
    attr = x.as_dict["attributes"]
    print([gdpoint["x"], gdpoint["y"], attr["Match_addr"], attr["Score"]])

"""***"""

import pandas as pd

df = pd.read_excel("direcciones.xlsx")
df.head()

df.columns

df["ADDRESS"] = df["DIRECCION "].apply(lambda x: x + ", Lima, PER")
df["x"] = 0
df["y"] = 0
df["Match_addr"] = ""
df["score"] = ""

df.head()

df.iloc[0]["APELLIDOS Y NOMBRES"]

def extractAddress(df, indice, idDf, address):
    gis = GIS()
    geocode_result = geocode(address = df.iloc[indice][address], as_featureset=True) # Cambiar la dirección
    for x in geocode_result.features:
        gdpoint = x.as_dict["geometry"]
        attr = x.as_dict["attributes"]
        df = df.append(pd.Series([df.iloc[indice][idDf], "", "", gdpoint["x"], gdpoint["y"], attr["Match_addr"], attr["Score"]], index=df.columns ), ignore_index=True)
    return df

for n in range(len(df)):
    df = extractAddress(df, n, "APELLIDOS Y NOMBRES", "ADDRESS")

df.sort_values(by='APELLIDOS Y NOMBRES')